// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230527180630_mig_addImageFile-ImageFileUrl")]
    partial class mig_addImageFileImageFileUrl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.Header", b =>
                {
                    b.Property<int>("HeaderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HeaderImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HeaderStatus")
                        .HasColumnType("bit");

                    b.Property<string>("HeaderTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HeaderID");

                    b.ToTable("Headers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ImageFile", b =>
                {
                    b.Property<int>("ImageFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageFileTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageFileID");

                    b.ToTable("ImageFiles");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductAvailability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ShoeBrandID")
                        .HasColumnType("int");

                    b.Property<int>("ShoeCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ShoeColorID")
                        .HasColumnType("int");

                    b.Property<int>("ShoePriceID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("ShoeBrandID");

                    b.HasIndex("ShoeCategoryID");

                    b.HasIndex("ShoeColorID");

                    b.HasIndex("ShoePriceID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ProductDiscount", b =>
                {
                    b.Property<int>("ProductDiscountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ProductDiscountDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductDiscountTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDiscountTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductDiscountID");

                    b.ToTable("ProductDiscounts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ServiceIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ShoeBrand", b =>
                {
                    b.Property<int>("ShoeBrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ShoeBrandName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoeBrandID");

                    b.ToTable("ShoeBrands");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ShoeCategory", b =>
                {
                    b.Property<int>("ShoeCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ShoeCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoeCategoryID");

                    b.ToTable("ShoeCategories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ShoeColor", b =>
                {
                    b.Property<int>("ShoeColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ShoeColorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoeColorID");

                    b.ToTable("ShoeColors");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ShoeDiscount", b =>
                {
                    b.Property<int>("ShoeDiscountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ShoeBrandID")
                        .HasColumnType("int");

                    b.Property<int>("ShoeCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ShoeColorID")
                        .HasColumnType("int");

                    b.Property<string>("ShoeDiscountAvailability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShoeDiscountDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShoeDiscountImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShoeDiscountModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ShoeDiscountNewPrice")
                        .HasColumnType("float");

                    b.Property<double>("ShoeDiscountPrice")
                        .HasColumnType("float");

                    b.Property<int>("ShoePriceID")
                        .HasColumnType("int");

                    b.HasKey("ShoeDiscountID");

                    b.HasIndex("ShoeBrandID");

                    b.HasIndex("ShoeCategoryID");

                    b.HasIndex("ShoeColorID");

                    b.HasIndex("ShoePriceID");

                    b.ToTable("ShoeDiscounts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ShoePrice", b =>
                {
                    b.Property<int>("ShoePriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ShoePriceMax")
                        .HasColumnType("int");

                    b.Property<int>("ShoePriceMin")
                        .HasColumnType("int");

                    b.HasKey("ShoePriceID");

                    b.ToTable("ShoePrices");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Product", b =>
                {
                    b.HasOne("EntityLayer.Concrete.ShoeBrand", "ShoeBrand")
                        .WithMany()
                        .HasForeignKey("ShoeBrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ShoeCategory", "ShoeCategory")
                        .WithMany()
                        .HasForeignKey("ShoeCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ShoeColor", "ShoeColor")
                        .WithMany()
                        .HasForeignKey("ShoeColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ShoePrice", "ShoePrice")
                        .WithMany()
                        .HasForeignKey("ShoePriceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoeBrand");

                    b.Navigation("ShoeCategory");

                    b.Navigation("ShoeColor");

                    b.Navigation("ShoePrice");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ShoeDiscount", b =>
                {
                    b.HasOne("EntityLayer.Concrete.ShoeBrand", "ShoeBrand")
                        .WithMany()
                        .HasForeignKey("ShoeBrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ShoeCategory", "ShoeCategory")
                        .WithMany()
                        .HasForeignKey("ShoeCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ShoeColor", "ShoeColor")
                        .WithMany()
                        .HasForeignKey("ShoeColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.ShoePrice", "ShoePrice")
                        .WithMany()
                        .HasForeignKey("ShoePriceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoeBrand");

                    b.Navigation("ShoeCategory");

                    b.Navigation("ShoeColor");

                    b.Navigation("ShoePrice");
                });
#pragma warning restore 612, 618
        }
    }
}
